# Change Requests — {{TASK_NAME}}

Per-task CR log. Generated by `scripts/new-task.sh` from
`.kiro/templates/task/change-requests.md.tpl`. Append one row per scope
suggestion. See `.kiro/steering/change-management.md` for type definitions
and the phase-approval gate, `.kiro/skills/raise-cr.md` for capture
playbook.

**Status legend:** `OPEN` (raised, not triaged) → `DECIDED` (type + decision set) → `DONE` (decision applied, `Propagated To` filled in if creep/cut).

**Type legend:** `bug` / `clarify` / `refine` / `creep` / `cut` / `UNCLASSIFIED` (pre-triage).

| ID   | When       | Phase / Stage                    | Source | Description                          | Type          | Status | Decision | Propagated To |
|------|------------|----------------------------------|--------|--------------------------------------|---------------|--------|----------|---------------|
| CR-0 | {{DATE}}   | bootstrap                        | template | (example row — delete on first real CR) "顺手加 CSV 导出" | creep         | DONE   | accept   | vision.md L42, requirements.md L18 |

<!--
Row template — copy and fill:

| CR-N | YYYY-MM-DD | <phase> / <stage>                | user   | "<verbatim or paraphrase>"           | UNCLASSIFIED  | OPEN   |          |               |

After triage, set Type + (Decision for creep/cut: accept/backlog/reject, else apply) + Status=DECIDED.
After applying (and propagating to vision.md/requirements.md if creep accepted), set Status=DONE and fill Propagated To.
-->
